#object that store enviroments variables that could be have sensitive data like a password
apiVersion: v1
kind: Secret
metadata:
  name: user-api-secret
  namespace: health-management
  labels:
    app: user-api
    #meant that we can use arbitrary key pair values
type: Opaque
data:
  database_user: cG9zdGdyZXM=
  database_password: cXdlcnR5
  database_url: amRiYzpwb3N0Z3Jlc3FsOi8vbG9jYWxob3N0OjU0MzIvdXNlcnMK
