apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-api
  namespace: health-management
  labels:
    app.kubernetes.io/name: medical-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medical-api
  template:
    metadata:
      labels:
        app: medical-api
    spec:
      containers:
      - name: medical-api
        image: andercl/health-management-medical-api:1.0.5 # {"$imagepolicy": "flux-system:medical-api"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8180
        env:
        - name: DATABASE_medical
          valueFrom:
            secretKeyRef:
              key: database_medical
              name: medical-api-secret
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database_password
              name: medical-api-secret
        - name: DATABASE_URL
          value: jdbc:postgresql://postgres-service.infra:5432/medical
