apiVersion: v1
kind: Service
metadata:
  name: medical-api-service
  namespace: health-management
  labels:
    app.kubernetes.io/name: medical-api
spec:
  ports:
  - name: medical-api-port
    port: 8380
    nodePort: 30783
  type: NodePort
  selector:
    app.kubernetes.io/name: medical-api