apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: health-management
spec:
  tls:
    - hosts:
        - health-management-pos-tccpuc.online
    - secretName: frontend-tls-secret
  rules:
    - host: health-management-pos-tccpuc.online
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80