apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: health-management
  labels:
    app.kubernetes.io/name: frontend
spec:
  ports:
  - name: frontend-port
    port: 3000
    targetPort: 3000
  type: NodePort
  selector:
    app.kubernetes.io/name: frontend