apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: health-management
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: frontend
