apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: health-management
  labels:
    app.kubernetes.io/name: frontend
spec:
  type: LoadBalancer
  ports:
  - name: frontend-port
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: frontend