apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: health-management
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app.kubernetes.io/name: frontend
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: frontend
  sessionAffinity: None