apiVersion: apps/v1
kind: Deployment
metadata:
  name: labs-api
  namespace: health-management
  labels:
    app.kubernetes.io/name: labs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labs-api
  template:
    metadata:
      labels:
        app: labs-api
    spec:
      containers:
      - name: labs-api
        image: andercl/health-management-labs-api:1.0.10 # {"$imagepolicy": "flux-system:labs-api"}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8380
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              key: database_labs
              name: labs-api-secret
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database_password
              name: labs-api-secret
        - name: DATABASE_URL
          value: jdbc:postgresql://postgres-service.infra:5432/labs
        - name: ENVIRONMENT
          value: production
