apiVersion: v1
kind: Service
metadata:
  name: labs-api-service
  namespace: health-management
  labels:
    app.kubernetes.io/name: labs-api
spec:
  ports:
  - name: labs-api-port
    port: 8180
    nodePort: 30780
  type: NodePort
  selector:
    app.kubernetes.io/name: labs-api