kind: Service
apiVersion: v1
metadata:
  name: postgres-service
  namespace: infra
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  #type: LoadBalancer
  type: NodePort
  selector:
   app: postgres
