apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.tookit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx/ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: my-ingress-nginx
        namespace: flux-system
      version: 0.10.3
  interval: 1m0s