---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: frontend
  namespace: health-management
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/theander/health-management-frontend

